version: "3"

services:

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    gateway:
        image: shipyardsuite/gateway:develop
        container_name: gateway
        ports:
            - "8080:8080"
            - "80:80"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./gateway/config/system.config.yml:/usr/src/app/config/system.config.yml
            - ./gateway/config/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        networks:
            - gateway

    documentation:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: documentation
        ports:
            - "3003:3003"
        networks:
            - gateway
        environment:
            SERVICE_PORT: 3003
            SERVICE_NAME: documentation
            HEALTHCHECK_ID: ${HEALTHCHECK_ID}
        healthcheck:
            test: curl --fail -s https://hc-ping.com/${HEALTHCHECK_ID} || exit 1
            interval: 20s
            timeout: 10s
            retries: 3

networks:
    gateway:
